name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-node@v3.8.0
        with:
          node-version: 16
          cache: 'npm'
      - name: Build web-app
        run: |
          npm ci
          npm run build
      - name: Deploy to deploy
        uses: peaceiris/actions-gh-pages@v3.9.3

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build